drop table users;

create table users
(USERNAME NVARCHAR2(20) NOT NULL,
SUBMIT NVARCHAR2(64) NOT NULL,
EMAIL NVARCHAR2(60) NOT NULL,
PRIMARY KEY (USERNAME));

COMMIT;

drop table infrastructure;
drop SEQUENCE SEQUENCE_ID;

CREATE SEQUENCE SEQUENCE_ID START WITH 1 INCREMENT BY 1;

create table infrastructure
(ID NUMBER (20) NOT NULL,
COST NVARCHAR2(20),
USERNAME NVARCHAR2(20) NOT NULL,
SERVICE NVARCHAR2(20) NOT NULL,
RAM NVARCHAR2(3) NOT NULL,
SSD NVARCHAR2(4) NOT NULL,
PACKAGEONE NVARCHAR2(1),
PACKAGETWO NVARCHAR2(6),
PACKAGETHREE NVARCHAR2(10),
PACKAGEFOUR NVARCHAR2(3),
PACKAGEFIVE NVARCHAR2(3),
PACKAGESIX NVARCHAR2(4),
PACKAGESEVEN NVARCHAR2(7),
PACKAGEEIGHT NVARCHAR2(12),
PACKAGENINE NVARCHAR2(7),
PACKAGETEN NVARCHAR2(11),
PACKAGEELEVEN NVARCHAR2(7),
PACKAGETWELVE NVARCHAR2(4),
PACKAGETHIRTEEN NVARCHAR2(12),
PACKAGEFOURTEEN NVARCHAR2(4),
PACKAGEFIFTEEN NVARCHAR2(4),
PACKAGESIXTEEN NVARCHAR2(3),
PACKAGESEVENTEEN NVARCHAR2(9),
PACKAGEEIGHTTEEN NVARCHAR2(8),
PACKAGENINETEEN NVARCHAR2(8),
PACKAGETWENTY NVARCHAR2(12),
PACKAGETWENTYONE NVARCHAR2(5),
SERVERS NVARCHAR2(20) NOT NULL,
VM NVARCHAR2(2) NOT NULL,
CPU NVARCHAR2(3) NOT NULL,
PRIMARY KEY (ID));

COMMIT;

-----------------------

drop table shareinfrastructure;

create table shareinfrastructure
(USERNAME NVARCHAR2(20),
SERVICE NVARCHAR2(20),
RAM NVARCHAR2(20),
SSD NVARCHAR2(20),
PACKAGEONE NVARCHAR2(20),
PACKAGETWO NVARCHAR2(20),
PACKAGETHREE NVARCHAR2(20),
PACKAGEFOUR NVARCHAR2(20),
PACKAGEFIVE NVARCHAR2(20),
PACKAGESIX NVARCHAR2(20),
PACKAGESEVEN NVARCHAR2(20),
PACKAGEEIGHT NVARCHAR2(20),
PACKAGENINE NVARCHAR2(20),
PACKAGETEN NVARCHAR2(20),
PACKAGEELEVEN NVARCHAR2(20),
PACKAGETWELVE NVARCHAR2(20),
PACKAGETHIRTEEN NVARCHAR2(20),
PACKAGEFOURTEEN NVARCHAR2(20),
PACKAGEFIFTEEN NVARCHAR2(20),
PACKAGESIXTEEN NVARCHAR2(20),
PACKAGESEVENTEEN NVARCHAR2(20),
PACKAGEEIGHTTEEN NVARCHAR2(20),
PACKAGENINETEEN NVARCHAR2(20),
PACKAGETWENTY NVARCHAR2(20),
PACKAGETWENTYONE NVARCHAR2(20),
SERVERS NVARCHAR2(20),
VM NVARCHAR2(20),
CPU NVARCHAR2(20));

COMMIT;

-----------------------

DROP TABLE LoginAttempts;

CREATE TABLE LoginAttempts
(USERNAME varchar(20) NOT NULL,
IP varchar(20) NOT NULL,
LOGINTIME varchar(20) NOT NULL,
LOGINATTEMPT INT NOT NULL,
PRIMARY KEY(IP)
);
COMMIT;
